input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.SmallDiamond)
    basic.pause(3000)
    basic.showIcon(IconNames.SmallSquare)
    basic.pause(3000)
    basic.showIcon(IconNames.Square)
    basic.pause(3000)
    basic.clearScreen()
})
input.onButtonPressed(Button.AB, function () {
    basic.showString("Hello")
    basic.showString("teacher")
    basic.pause(2000)
    basic.showIcon(IconNames.SmallHeart)
    basic.showIcon(IconNames.Heart)
    basic.pause(2000)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    basic.showString("47")
    basic.pause(2000)
    basic.showString("Puri")
    basic.pause(2000)
    basic.clearScreen()
})
basic.showString("Purichaya Tubwong")
basic.pause(3000)
basic.showString("4/2")
basic.pause(3000)
